[package]
name = "hello-hyper"
version = "0.1.0"
authors = ["jbowen93 <jish.bowen@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = { git = "https://github.com/hyperium/hyper" }
env_logger = "0.3"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-timer = "0.1"